name: 'etcd-runner'
description: 'etcd runner'

runs:
  using: "composite" # Mandatory parameter
  steps:
    - name: Start ETCD
      shell: bash
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/etcd.sh"
        "${GITHUB_WORKSPACE}/.github/etcd.sh"