# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main
      - metadata_v2
  pull_request:
    branches: 
      - main

jobs:
  builds:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        java: [ 8, 11, 15 ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: run zk
      run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
          "${GITHUB_WORKSPACE}/.github/zk.sh"
    - name: run iotdb
      run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/iotdb.sh"
          "${GITHUB_WORKSPACE}/.github/iotdb.sh"
    - name: Install with Maven
      run: mvn clean install -DskipTests
    - name: move dependencies
      run: cp "${GITHUB_WORKSPACE}/iotdb/target/iotdb-0.1.0-SNAPSHOT.jar" "${GITHUB_WORKSPACE}/core/lib/iotdb-0.1.0-SNAPSHOT.jar"
    - name: check is dependency moved
      run: ls "${GITHUB_WORKSPACE}/core/lib/"
    - name: start Iginx
      run: |
          chmod +x "${GITHUB_WORKSPACE}/start.sh"
          "${GITHUB_WORKSPACE}/start.sh"
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Coverage report
      run: mvn -B verify -P coverage --no-transfer-progress
    - uses: codecov/codecov-action@v1
      with:
        file: ./**/target/site/jacoco/jacoco.xml
        name: codecov
