name: "Scale-out-On-IoTDB"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  VERSION: 0.6.0-SNAPSHOT

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  IoTDB-Tag-Test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
        DB-name: [ "iotdb11", "iotdb12" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Environmet Dependence
        uses: ./.github/actions/dependence
        with:
          python-version: ${{ matrix.python-version }}
          java: ${{ matrix.java }}

      - name: Run ZooKeeper
        uses: ./.github/actions/zookeeperRunner

      - name: Run IoTDB
        uses: ./.github/actions/iotdbRunner
        with:
          version: ${{matrix.DB-name}}

      - name: Change pom
        run: |
          mv test/pom.xml test/pom.xml.backup
          mv test/pom.xml.${{matrix.DB-name}} test/pom.xml
          ls test/pom*

      - name: Install IginX with Maven
        shell: bash
        run: |
          mvn clean package -DskipTests

      #第 1 阶段测试开始==========================================
      - name: Prepare CapExp environment
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriNoDataExpNoData

      - name: OriNoDataExpNoData IT
        run: mvn test -q -Dtest=IoTDBTagScaleOutIT#OriNoDataExpNoData_IT -DfailIfNoTests=false

      #第 2 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriHasDataExpNoData

      - name: OriHasDataExpNoData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBTagScaleOutIT#OriHasDataExpNoData_IT -DfailIfNoTests=false

      #第 3 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriNoDataExpHasData

      - name: OriNoDataExpHasData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBTagScaleOutIT#OriNoDataExpHasData_IT -DfailIfNoTests=false

      #第 4 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriHasDataExpHasData

      - name: OriHasDataExpHasData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBTagScaleOutIT#OriHasDataExpHasData_IT -DfailIfNoTests=false

      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov

  IoTDB-SQLSession-Test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
        DB-name: [ "iotdb11", "iotdb12" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Environmet Dependence
        uses: ./.github/actions/dependence
        with:
          python-version: ${{ matrix.python-version }}
          java: ${{ matrix.java }}

      - name: Run ZooKeeper
        uses: ./.github/actions/zookeeperRunner

      - name: Run IoTDB
        uses: ./.github/actions/iotdbRunner
        with:
          version: ${{matrix.DB-name}}

      - name: Change pom
        run: |
          mv test/pom.xml test/pom.xml.backup
          mv test/pom.xml.${{matrix.DB-name}} test/pom.xml
          ls test/pom*

      - name: Install IginX with Maven
        shell: bash
        run: |
          mvn clean package -DskipTests

      #第 1 阶段测试开始==========================================
      - name: Prepare CapExp environment
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriNoDataExpNoData

      - name: OriNoDataExpNoData IT
        run: mvn test -q -Dtest=IoTDBSqlScaleOutIT#OriNoDataExpNoData_IT -DfailIfNoTests=false

      #第 2 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriHasDataExpNoData

      - name: OriHasDataExpNoData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBSqlScaleOutIT#OriHasDataExpNoData_IT -DfailIfNoTests=false

      #第 3 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriNoDataExpHasData

      - name: OriNoDataExpHasData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBSqlScaleOutIT#OriNoDataExpHasData_IT -DfailIfNoTests=false

      #第 4 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriHasDataExpHasData

      - name: OriHasDataExpHasData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBSqlScaleOutIT#OriHasDataExpHasData_IT -DfailIfNoTests=false

      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov

  IoTDB-Session-Test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
        DB-name: [ "iotdb11", "iotdb12" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Environmet Dependence
        uses: ./.github/actions/dependence
        with:
          python-version: ${{ matrix.python-version }}
          java: ${{ matrix.java }}

      - name: Run ZooKeeper
        uses: ./.github/actions/zookeeperRunner

      - name: Run IoTDB
        uses: ./.github/actions/iotdbRunner
        with:
          version: ${{matrix.DB-name}}

      - name: Change pom
        run: |
          mv test/pom.xml test/pom.xml.backup
          mv test/pom.xml.${{matrix.DB-name}} test/pom.xml
          ls test/pom*

      - name: Install IginX with Maven
        shell: bash
        run: |
          mvn clean package -DskipTests

      #第 1 阶段测试开始==========================================
      - name: Prepare CapExp environment
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriNoDataExpNoData

      - name: OriNoDataExpNoData IT
        run: mvn test -q -Dtest=IoTDBSessionScaleOutIT#OriNoDataExpNoData_IT -DfailIfNoTests=false

      #第 2 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriHasDataExpNoData

      - name: OriHasDataExpNoData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBSessionScaleOutIT#OriHasDataExpNoData_IT -DfailIfNoTests=false

      #第 3 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriNoDataExpHasData

      - name: OriNoDataExpHasData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBSessionScaleOutIT#OriNoDataExpHasData_IT -DfailIfNoTests=false

      #第 4 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriHasDataExpHasData

      - name: OriHasDataExpHasData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBSessionScaleOutIT#OriHasDataExpHasData_IT -DfailIfNoTests=false

      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov

  IoTDB-Rest-Test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        java: [ 8 ]
        python-version: [ "3.7" ]
        os: [ ubuntu-latest, macos-latest ]
        DB-name: [ "iotdb11", "iotdb12" ]
#        os: [ ubuntu-latest ]
#        DB-name: [ "iotdb11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Environmet Dependence
        uses: ./.github/actions/dependence
        with:
          python-version: ${{ matrix.python-version }}
          java: ${{ matrix.java }}

      - name: Run ZooKeeper
        uses: ./.github/actions/zookeeperRunner

      - name: Run IoTDB
        uses: ./.github/actions/iotdbRunner
        with:
          version: ${{matrix.DB-name}}

      - name: Change pom
        run: |
          mv test/pom.xml test/pom.xml.backup
          mv test/pom.xml.${{matrix.DB-name}} test/pom.xml
          ls test/pom*

      - name: Install IginX with Maven
        shell: bash
        run: |
          mvn clean package -DskipTests

      #第 2 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriHasDataExpNoData

      - name: OriHasDataExpNoData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBRestfulScaleOutIT#OriHasDataExpNoData_IT -DfailIfNoTests=false

      #第 1 阶段测试开始==========================================

#      - name: Clear Data
#        if: always()
#        run: |
#          echo "" > ./.github/actions/iginxRunner/iginxLog.txt
#          echo "" > ./.github/actions/iotdbRunner/iotdb2Log.txt
#          echo "" > ./.github/actions/iotdbRunner/iotdb1Log.txt

      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriNoDataExpNoData

      - name: OriNoDataExpNoData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBRestfulScaleOutIT#OriNoDataExpNoData_IT -DfailIfNoTests=false

#      - name: Check the Iginx Logs
#        if: always()
#        run: |
#          echo "IGINX============================================================================="
#          cat ./.github/actions/iginxRunner/iginxLog.txt
#
#      - name: Check the iotdb1 Logs
#        if: always()
#        run: |
#          echo "IOTDB1============================================================================="
#          cat ./.github/actions/iotdbRunner/iotdb1Log.txt
#
#      - name: Check the iotdb2 Logs
#        if: always()
#        run: |
#          echo "IOTDB2============================================================================="
#          cat ./.github/actions/iotdbRunner/iotdb2Log.txt

      #第 3 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriNoDataExpHasData

      - name: OriNoDataExpHasData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBRestfulScaleOutIT#OriNoDataExpHasData_IT -DfailIfNoTests=false

      #第 4 阶段测试开始==========================================
      - name: Prepare CapExp environment
        if: always()
        uses: ./.github/actions/capacityExpansionUnionTest
        with:
          version: ${VERSION}
          DB-name: ${{matrix.DB-name}}
          Test-Way: OriHasDataExpHasData

      - name: OriHasDataExpHasData IT
        if: always()
        run: mvn test -q -Dtest=IoTDBRestfulScaleOutIT#OriHasDataExpHasData_IT -DfailIfNoTests=false

      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov