name: "UTTest"

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
env:
  VERSION: 0.6.0-SNAPSHOT

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Unit-Test:
    strategy:
      fail-fast: false
      matrix:
        java: [ 8 ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Environmet Dependence
        uses: ./.github/actions/dependence
        with:
          java: ${{ matrix.java }}

      - name: Test with Maven
        run: mvn clean package -pl core -am
